table 'Age Groups'
	lineageTag: 4fa12b57-3de6-4988-bd82-26378bc04bd9

	column 'Age Groups ID'
		dataType: int64
		formatString: 0
		lineageTag: 0395020b-a1b0-4cf1-b894-63e0d26984ed
		summarizeBy: none
		sourceColumn: Age Groups ID

		annotation SummarizationSetBy = Automatic

	column 'Age Groups'
		dataType: string
		lineageTag: 48ea23cb-2daf-4562-9841-dd83fc91ff2d
		summarizeBy: none
		sourceColumn: Age Groups
		sortByColumn: 'Age Groups ID'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Age Groups' = m
		mode: import
		source =
				let
				    Source = #"Customer Data",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Age Groups"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Duplicates", "Age Groups ID", each if [Age Groups] = "<=20" then 1 else if [Age Groups] = "21-30" then 2 else if [Age Groups] = "31-40" then 3 else if [Age Groups] = "41-50" then 4 else if [Age Groups] = "51-60" then 5 else if [Age Groups] = "61-70" then 6 else if [Age Groups] = ">=71" then 7 else null),
				    #"Sorted Rows" = Table.Sort(#"Added Conditional Column",{{"Age Groups ID", Order.Ascending}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Sorted Rows",{"Age Groups ID", "Age Groups"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns",{{"Age Groups ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

